# Generated by Django 5.0.4 on 2024-06-27 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('branch_phone', models.CharField(max_length=15)),
                ('side_code', models.CharField(max_length=10)),
                ('branch_email', models.EmailField(max_length=100)),
                ('branch_address', models.TextField()),
                ('branch_location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=100)),
                ('latt', models.CharField(max_length=100)),
                ('country_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('area_name', models.CharField(max_length=100)),
                ('branch_image', models.ImageField(upload_to='uploads/branch_images/')),
                ('status', models.BooleanField(default=True)),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
