# Generated by Django 5.0.4 on 2024-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountheads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthead',
            name='accountNo',
            field=models.CharField(max_length=50),
        ),
    ]
