# Generated by Django 5.0.4 on 2024-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='image',
            field=models.ImageField(upload_to='uploads/review_rating_images/'),
        ),
    ]
