<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-07-05 08:47

import django.db.models.deletion
=======
=======
>>>>>>> 40ab15fc84cefaff8effe36b087af5f719030c8a
# Generated by Django 5.0.4 on 2024-07-02 09:57

import django.db.models.deletion
import utils.common_helpers
<<<<<<< HEAD
>>>>>>> 657db95 (Payment Complete)
=======
>>>>>>> 40ab15fc84cefaff8effe36b087af5f719030c8a
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquirer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
<<<<<<< HEAD
                ('encription_key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('prod_url', models.URLField()),
                ('prod_key', models.CharField(max_length=255)),
                ('prod_secret', models.CharField(max_length=255)),
                ('sandbox_url', models.URLField()),
                ('sandbox_key', models.CharField(max_length=255)),
                ('sandbox_secret', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cards', models.CharField(max_length=255)),
=======
=======
>>>>>>> 40ab15fc84cefaff8effe36b087af5f719030c8a
                ('name', models.CharField(max_length=100, unique=True, validators=[utils.common_helpers.validate_name])),
                ('encription_key', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('prod_url', models.CharField(max_length=100)),
                ('prod_key', models.CharField(max_length=100)),
                ('prod_secret', models.CharField(max_length=100)),
                ('sandbox_url', models.CharField(max_length=100)),
                ('sandbox_key', models.CharField(max_length=100)),
                ('sandbox_secret', models.CharField(max_length=100)),
                ('min_value', models.CharField(max_length=100)),
                ('max_value', models.CharField(max_length=100)),
                ('daily_value', models.CharField(max_length=100)),
                ('cards', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
<<<<<<< HEAD
>>>>>>> 657db95 (Payment Complete)
=======
>>>>>>> 40ab15fc84cefaff8effe36b087af5f719030c8a
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
