# Generated by Django 5.0.4 on 2024-06-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('side', models.CharField(max_length=100)),
                ('sample', models.ImageField(upload_to='documents/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
