# Generated by Django 5.0.4 on 2024-06-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(upload_to='uploads/blog_category_images/'),
        ),
    ]
