# Generated by Django 5.0.4 on 2024-06-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0002_alter_blogcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='date',
            field=models.DateField(),
        ),
    ]
