# Generated by Django 5.0.4 on 2024-06-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0003_alter_blogcategory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='date',
        ),
    ]
