# Generated by Django 5.0.2 on 2024-06-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_date_created_customuser_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('user', 'User'), ('merchant', 'Merchant')], default='merchant', max_length=20),
        ),
    ]
